DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (40) UNIQUE NOT NULL,
    devoured BOOLEAN
)